[sources.in]
type = "host_metrics"

# [sources.prom]
# type = "prometheus_scrape"
# endpoints = [ "http://localhost:9100/metrics" ]

[sinks.out]
inputs = ["in"]
type = "greptimedb"
endpoint = "localhost:4001"

# [sinks.cloud]
# inputs = ["in"]
# type = "greptimedb"
# endpoint = "ri90pr79jvuf.test-ap-southeast-1.aws.greptime.cloud:4001"
# dbname = "rhe8afku6uws-test"
# username = "8eXxD6lHdbDYBVByQ0KjDsvp"
# password = "I7vppnCLFCaJevlGlf5dUBzX"
